### ISSUE TITLE
Updating the date.js library

### ISSUE THREAD

**Issue by thapar** [blairkutz/email-delay-send#2]
Hi Blair,
Can we get this great project back up and running?

**Comment by blairkutz** [comment]
Hello Thapar,

I'm open to any pull requests as long as they are backwards compatible.

What updates to date.js did you have in mind? It looks like there hasn't been much work on date.js since 2015 (besides some work with French parsing): https://github.com/datejs/Datejs/commits/master

Thanks,
-Blair

**Comment by nateritter** [comment]
I'd be interested in getting this running again also. Happy to help. Why was date.js removed in the first place?  If I know the issue, perhaps I can help solve it.

**Comment by blairkutz** [comment]
Hello nateritter,

Thanks for the offer to help out  :-)

As far as I know, nothing in the project is broken and date.js hasn't been removed or anything important updated since it was added.

(Clearing up some confusion)
Originally the project was called 'Gmail Delay Send' and all code was posted here. I was informed by Google that I couldn't use the name 'Gmail' in any personal project. I intended to migrate this project to 'Email Delay Send' (the project you're on now), but still haven't actually done it.

Date.js and all the current code can be found on the gmail-delay-send site here: https://github.com/blairkutz/gmail-delay-send/blob/master/v2/src/datejs

If you would like to help out with the project though, this issue could use some attention: https://groups.google.com/forum/#!topic/gmaildelaysend/nhQDziZXEBA/discussion

Thanks!
-Blair
